= 第一个Node.JS应用
:toc: left
:toc-title: Table of Contents
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:sectanchors:
:sectlinks:
:partnums:

. 导入Node.js自带的 ``http ``模块 `var http = require("http");`
. 创建服务器 `+http.createServer(function(request, response){ ...
})+`
.. 写入返回头信息 `response.writeHead(200, {"Content-Type": "text/plain"});`
.. 写入返回值 `response.end("Hello World\n");`
. 监听指定端口 `http.createServer().listen(8888)`
. 使用 `node.js` 执行上面的代码 `node server.js`
. 浏览器打开 `localhost:8888`

[source,js]
----
// 载入Node.js自带的htp模块Http模块
var http = require("http");

// 创建服务器
http.createServer(function(request, response) {
	// 发送 HTTP 头部
	// HTTP 状态值: 200 : OK
	// 内容类型: text/plain
	response.writeHead(200, {
		"Content-Type": "text/plain"
	});

	// 响应数据
	response.end("Hello World\n");
}).listen(8888);

// 终端打印如下信息
console.log('Server running at http://127.0.0.1:8888/');
----

== npm

* 安装：保存在工程目录下的 `node_modules` 的目录中

[source,shell]
----
$ npm install <Module Name>
$ npm install express
----

* 全局安装（带参数 -g）：默认保存在 `%user%\AppData\Roaming\npm\node_modules`
* 查看(模块)安装信息

[source,shell]
----
$ npm list
$ npm list <模块-可省略> -g
----

* 卸载：`npm uninstall <Module Name>`
* 更新：`npm update <Module Name>`
* 查看：`npm ls`
* 搜索：`npm serach <Module Name>`
* 创建模块
** 必须拥有 `package.json` 文件
** 使用 `npm init` 帮助生成 `package.json` ·文件
** 添加用户：`npm adduser`
** 发布模块：`npm publish`

=== 版本号

使用NPM下载和发布代码时都会接触到版本号。NPM使用语义版本号来管理代码，这里简单介绍一下。 语义版本号分为X.Y.Z三位，分别代表主版本号、次版本号和补丁版本号。当代码变更时，版本号按以下原则更新。

* 如果只是修复bug，需要更新Z位。
* 如果是新增了功能，但是向下兼容，需要更新Y位。
* 如果有大变动，向下不兼容，需要更新X位。

版本号有了这个保证后，在申明第三方包依赖时，除了可依赖于一个固定版本号外，还可依赖于某个范围的版本号。例如"argv": "0.0.x"表示依赖于0.0.x系列的最新版argv。

== 回调函数

____
`Node.js` 中所有API都支持回调函数 `Node.js` 异步编程的最直接体现就是回调函数，回调函数一般作为 `API` 的最后一个参数出现 使用 `WeebStorm` 简历 `Node.js` 项目
____

*阻塞代码*

[source,js]
----
let fs = require("fs");

let data = fs.readFileSync("package.json")
console.log(data.toString());
console.log("End!");
----

*非阻塞*

[source,js]
----
// 导入fs模块
let fs = require("fs");

fs.readFile("package.json", function (err, buffer) {
    if (err) return console.error(err);
    console.log(buffer.toString());
} )
console.log("End!");
----

== 事件

=== 事件驱动程序

[source,js]
----
let events = require("events");
let eventEmitter = new events.EventEmitter();

let connectionHandler = function () {
    console.log("Connect Success!");
    eventEmitter.emit("data_received");
}

let dataReceivedHandler = function () {
    console.log("Data received success.")
}

eventEmitter.on("connection", connectionHandler);
eventEmitter.on("data_received", dataReceivedHandler);

eventEmitter.emit("connection");

console.log("End.")

// 输出
// Connect Success!
// Data received success.
// End.
----
